[logger]
level = "INFO"

[db]
in_memory = true
dsn = "host=localhost port=5432 user=admin password=admin dbname=event sslmode=disable"
migration = "migrations"

[http]
host = "localhost"
port = "8080"
